name: OntaDev_Libs
version: '${project.version}'
main: com.ontadev.libs.plugin.OntaDev_Libs
api-version: '1.16'
load: STARTUP
authors: [ OntaDev ]

depend:
  - LuckPerms

soft-depend:
  - OntaDev_Installer
